# Generated by Django 5.0.3 on 2025-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_section_content_type_section_pdf_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/'),
        ),
        migrations.AddField(
            model_name='section',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID for embedding', max_length=100, null=True),
        ),
    ]
