# Generated by Django 5.1.7 on 2025-04-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_file'),
    ]

    operations = [
    ]
