# Generated by Django 5.0.3 on 2025-04-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_file_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('both', 'Both Video & PDF'), ('text', 'Text Content'), ('quiz', 'Quiz')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='module_pdfs/'),
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID for embedding', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
