# Generated by Django 5.0.3 on 2025-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_pdf_to_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pdf_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_content_type',
            field=models.CharField(blank=True, default='application/pdf', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
