# Generated by Django 5.0.3 on 2025-04-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_module_pdf_binary_module_pdf_content_type_and_more'),
    ]

    operations = [
    ]
