# Generated by Django 5.0.2 on 2025-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_add_pdf_binary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether the course is free or paid'),
        ),
    ]
